/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.Medico.*;
/**
 *
 * @author emil
 */
public class MedicoView extends javax.swing.JFrame {

    private final model.Medico m;
    /**
     * Creates new form MedicoView
     */
    public MedicoView(model.Medico m) {
        this.m = m;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Esci = new javax.swing.JButton();
        Utente = new javax.swing.JLabel();
        CompilaPrescrizioni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Esci.setText("ESCI");
        Esci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EsciMouseClicked(evt);
            }
        });

        Utente.setText("Medico "+m.getTipo()+" "+m.getName()+" "+m.getCognome());

        CompilaPrescrizioni.setText("Effettua Prescrizione");
        CompilaPrescrizioni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompilaPrescrizioniMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Esci)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CompilaPrescrizioni)
                    .addComponent(Utente, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Utente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CompilaPrescrizioni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(Esci)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EsciMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EsciMouseClicked
        Login.occupied=false;
        dispose();
    }//GEN-LAST:event_EsciMouseClicked

    private void CompilaPrescrizioniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompilaPrescrizioniMouseClicked
        control.MedicoControl.effettuaPrescrizioni();
    }//GEN-LAST:event_CompilaPrescrizioniMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompilaPrescrizioni;
    private javax.swing.JButton Esci;
    private javax.swing.JLabel Utente;
    // End of variables declaration//GEN-END:variables
}
